import './globals.css'
import TopNav from './topnav'
import Footer from './footer'
import 'bootstrap/dist/css/bootstrap.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="body">
          <TopNav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
